Add blog post: Building an SGX profiler for Gramine
gramineproject/gramineproject.io pull request #4
Opened 2022-05-10 15:01 UTC by pwmarcz

2022-05-10 15:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: 0 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1iUXRi7LeVdUAnsK2s:-N1iUXRk8Noy-KALyJ9O:boozpc6) (no related file):*
FYI: This is the first draft, so I might have to reword it significantly.

___
___
*[`content/blog/sgx-profiler/contents.lr` line 5 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1iUQ0v2dHFSFyPBjKq:-N1iUQ0v2dHFSFyPBjKr:bgjeec6) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L5)):*
> ```Markdown
> author: Paweł Marczewski
> ---
> pub_date: 2022-05-10
> ```

TODO before merging: update date
___
*[`content/blog/sgx-profiler/contents.lr` line 12 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1iUVgE-uYcXX8ud81h:-N1iUVgE-uYcXX8ud81i:b38y84o) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L12)):*
> ```Markdown
> 
> *This blog post describes how I developed the SGX profiling mode for Gramine.
> Thanks to (TODO) for reviewing.*
> ```

TODO: update reviewers


<!-- Sent from Reviewable.io -->

2022-05-11 08:34 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1ltYDNE8EMPzJabYpZ:-N1ltYDNE8EMPzJabYp_:bujw71b) (no related file):*
When I run this with `lektor serve`, I see the previous blog post ("GDB support inside Gramine's SGX enclaves") with *black font on black background*. This only happens on the http://127.0.0.1:5000/blog/ page. When I move to the actual "GDB support ..." page (http://127.0.0.1:5000/blog/gdb-support-in-gramine/), the text is restored to sanity -- white font on black background.

What is the deal with this?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1mF9Jn1kWZ6u4UKgQx:-N1mF9Jn1kWZ6u4UKgQy:bbtkbhp) (no related file):*
Awesome article!

___
___
*[`content/blog/sgx-profiler/contents.lr` line 14 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lxKWy7NcOPlE1mGYM:-N1lxKWy7NcOPlE1mGYN:b4l3j8j) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L14)):*
> ```Markdown
> Thanks to (TODO) for reviewing.*
> 
> As mentioned in [the last blog post][prev], [Gramine] is a framework for running
> ```

I think you should split this sentence into two:
- "Gramine is a framework ..."
- "In the previous post, I described the GDB support for Gramine ..."

And then, with a new paragraph, "It is quite possible ..."

Otherwise it reads weird -- why do you start with GDB support before even introducing what Gramine is? How is GDB support related to performance overhead of Gramine (it is not related)? I think my proposed introduction is better in this sense.
___
*[`content/blog/sgx-profiler/contents.lr` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lyNLN94_3aN5ia7Dc:-N1lyNLN94_3aN5ia7Dd:b-7r4soa) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L17)):*
> ```Markdown
> Linux applications under non-standard environments. It's quite possible that
> running an application under Gramine will have some performance overhead. By
> using a profiler, we can find out what it is, and how to fix it: we might be
> ```

A link to some Wiki or blog about profilers and/or `perf` specifically? I love https://www.brendangregg.com/perf.html, though you introduce `perf` below and here you want a more general description.
___
*[`content/blog/sgx-profiler/contents.lr` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lyJJUE4Kv5jSY24np:-N1lyJJUE4Kv5jSY24nq:b-f8y7ia) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L18)):*
> ```Markdown
> running an application under Gramine will have some performance overhead. By
> using a profiler, we can find out what it is, and how to fix it: we might be
> able to fix the problem in Gramine, or, if the inefficiency is inherent to the
> ```

`fix the problem` -> `fix a performance bug`?
___
*[`content/blog/sgx-profiler/contents.lr` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lymoz7f8T8DN2ibVS:-N1lymp-6NXCnvzu4x26:b47xic5) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L20)):*
> ```Markdown
> able to fix the problem in Gramine, or, if the inefficiency is inherent to the
> environment (e.g. the way SGX memory is managed), it might be possible to tweak
> or patch the application to do something else.
> ```

`to do something else` -> `to circumvent these environment idiosyncrasies`
___
*[`content/blog/sgx-profiler/contents.lr` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lzXrY0Yg_f__NaKCE:-N1lzXrZ07GxyG9E2BIF:b7qzcp6) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L25)):*
> ```Markdown
> [prev]: https://gramineproject.io/blog/gdb-support-in-gramine/
> 
> Unfortunately, similar to GDB, Gramine's SGX mode does not support profiling
> ```

`to GDB` -> `to debugging with GDB`
___
*[`content/blog/sgx-profiler/contents.lr` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lzxCL-GrUj4ZjGu_c:-N1lzxCL-GrUj4ZjGu_d:b-9isf07) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L27)):*
> ```Markdown
> Unfortunately, similar to GDB, Gramine's SGX mode does not support profiling
> tools out of the box: by default, the code executing inside an SGX enclave is
> opaque to external tools. This blog posts describes how I built my own solution
> ```

`This blog post`
___
*[`content/blog/sgx-profiler/contents.lr` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m-0FGBFsq0kJN98E3:-N1m-0FGBFsq0kJN98E4:b-kmseik) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L27)):*
> ```Markdown
> Unfortunately, similar to GDB, Gramine's SGX mode does not support profiling
> tools out of the box: by default, the code executing inside an SGX enclave is
> opaque to external tools. This blog posts describes how I built my own solution
> ```

Is it fine to say `I built my own solution`? I don't mind this "selfish" way of saying this, just reads weirdly. Maybe `I added support for profiling Gramine`? It's not like you built a new tool.
___
*[`content/blog/sgx-profiler/contents.lr` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m-dHGDiX9TTf1PdmO:-N1m-dHH6gcp_P8kFqT-:bmf6hn5) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L35)):*
> ```Markdown
> Linux profiler built into the Linux kernel. By running `perf record`, we can ask
> Linux to record a trace of program execution. Then, `perf report` will interpret
> that data and show time spent in each function.
> ```

Maybe add `Here is an example of the report from perf:` ?
___
*[`content/blog/sgx-profiler/contents.lr` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m1yV06ZMHYSN1af4w:-N1m1yV06ZMHYSN1af4x:bht9t50) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L42)):*
> ```Markdown
> 
> The architecture of `perf` is pretty interesting: the recording tool, `perf
> record`, actually asks the Linux kernel to monitor the process (using the
> ```

You skipped the first step: `perf record` must spawn a process-to-monitor or attach to it. Otherwise it reads like `perf record` just asks the Linux kernel to monitor *some random process*.

Also, `perf record` must learn about the addresses where code from different binaries is loaded into, you also don't describe this step here. UPDATE: Ok, you describe it below. Please still add some text here and say "(see below)".
___
*[`content/blog/sgx-profiler/contents.lr` line 43 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m1K7F-InWMSigfBAr:-N1m1K7F-InWMSigfBAs:bfbukws) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L43)):*
> ```Markdown
> The architecture of `perf` is pretty interes [...]

2022-05-12 12:48 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: 5 of 9 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1ltYDNE8EMPzJabYpZ:-N1rZwwE2mN5Q-5Zp8Kl:b-brshyh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When I run this with `lektor serve`, I see the previous blog post ("GDB support inside Gramine's SGX enclaves") with *black font on black background*. This only happens on the http://127.0.0.1:5000/blog/ page. When I move to the actual "GDB support ..." page (http://127.0.0.1:5000/blog/gdb-support-in-gramine/), the text is restored to sanity -- white font on black background.

What is the deal with this?
</blockquote></details>

Wow, good catch. I messed up the CSS hack for inverting colors, and it ended up inverting *everything*. Fixed.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1mF9Jn1kWZ6u4UKgQx:-N1r_9Sz6vTLc4_Ib_Qy:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome article!
</blockquote></details>

Thanks!

___
___
*[`content/blog/sgx-profiler/contents.lr` line 17 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lyNLN94_3aN5ia7Dc:-N1rfNIA0hYD9cEOzkTl:blyp029) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A link to some Wiki or blog about profilers and/or `perf` specifically? I love https://www.brendangregg.com/perf.html, though you introduce `perf` below and here you want a more general description.
</blockquote></details>

I added a link to Wikipedia.
___
*[`content/blog/sgx-profiler/contents.lr` line 18 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lyJJUE4Kv5jSY24np:-N1rfWNV6tZAnFWUMiDH:b-qj92pf) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`fix the problem` -> `fix a performance bug`?
</blockquote></details>

Reworded.
___
*[`content/blog/sgx-profiler/contents.lr` line 20 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lymoz7f8T8DN2ibVS:-N1rfXah6I6rtnqoo5DA:brn9u14) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to do something else` -> `to circumvent these environment idiosyncrasies`
</blockquote></details>

Actually I decided I don't want to go too deep in that direction. I reworded to emphasize "understanding the problem better".
___
*[`content/blog/sgx-profiler/contents.lr` line 25 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1lzXrY0Yg_f__NaKCE:-N1rg1RT4OlwrrFRTRq_:b-8v5evb) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to GDB` -> `to debugging with GDB`
</blockquote></details>

Changed to "similar to what we've seen".
___
*[`content/blog/sgx-profiler/contents.lr` line 27 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m-0FGBFsq0kJN98E3:-N1rgxaK4boP0wl3pdhX:b-istk5i) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it fine to say `I built my own solution`? I don't mind this "selfish" way of saying this, just reads weirdly. Maybe `I added support for profiling Gramine`? It's not like you built a new tool.
</blockquote></details>

Well, it's a combination of completely custom code and piggy-backing on `perf`. For instance, I don't think "I added `perf` support" is accurate either :)

I reworded this paragraph to give a better summary of the end result.
___
*[`content/blog/sgx-profiler/contents.lr` line 35 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m-dHGDiX9TTf1PdmO:-N1rjcrCBcqkZ0kP6jbJ:b-896fix) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add `Here is an example of the report from perf:` ?
</blockquote></details>

Done.
___
*[`content/blog/sgx-profiler/contents.lr` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m1yV06ZMHYSN1af4w:-N1rkXjj-Tz50FyC3LQ2:b-tlz79) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You skipped the first step: `perf record` must spawn a process-to-monitor or attach to it. Otherwise it reads like `perf record` just asks the Linux kernel to monitor *some random process*.

Also, `perf record` must learn about the addresses where code from different binaries is loaded into, you also don't describe this step here. UPDATE: Ok, you describe it below. Please still add some text here and say "(see below)".
</blockquote></details>

I don't think it's important whether `perf record` is the one spawning a process, so I added a mention that it "monitors a running process".

I also added details about mapping executables and converting addresses. I also added that detail to the diagram.
___
*[`content/blog/sgx-profiler/contents.lr` line 44 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m0uex9f26P7DYCLA7:-N1rq4e8CPq42EpeEt2o:bbxju7g) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`some program state` doesn't sound right here. My first association is the snapshot of memory of the process, but in reality it is a bunch of CPU registers and HW counters. So I'd remove `some program state` and be more specific: `...contain instruction pointer, stack pointer, HW counters, etc.`.
</blockquote></details>

How about "execution state"?
___
*[`content/blog/sgx-profiler/contents.lr` line 61 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m2uxo8CmE_7-vrxds:-N1rqU0vCpEx78jh0_-r:b-dfqzuh) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`GDB needed some extra help` link doesn't render correctly.
</blockquote></details>

I intended it to be a link to the previous article, but I already link to it twice, so maybe no need to add another one. Converted to normal text.
___
*[`content/blog/sgx-profiler/contents.lr` line 65 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m3AKcBGtoz9ff_5Q8:-N1rqkx7DhdT6qYhuUTv:bhnuj) ([raw file [...]

2022-05-13 08:37 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[`content/blog/sgx-profiler/contents.lr` line 42 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m1yV06ZMHYSN1af4w:-N1wUqTo-vkceaVEOMSi:ba9muoy) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't think it's important whether `perf record` is the one spawning a process, so I added a mention that it "monitors a running process".

I also added details about mapping executables and converting addresses. I also added that detail to the diagram.
</blockquote></details>

The newly added details on the diagram are awesome!
___
*[`content/blog/sgx-profiler/contents.lr` line 77 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1m4JgtD9bUwj54eO9Y:-N1wW2m12AOVsnOKT2Tw:bv2soo5) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L77)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

But it *cannot* be done in ring-3, not with `perf`. `perf record` does not stop the process, it relies on Linux (cheaply!) recording the data in scheduler, when the process is interrupted anyway. Doing it from userspace means essentially writing a different profiler, with higher overhead.

So, I think SGX support in `perf record` / `perf_event_open()` kernel syscall would be pretty useful, although of course upstreaming it might be not feasible.

Anyway, I removed speculation about modifying the Linux kernel.
</blockquote></details>

Ok, thanks for the explanation about `perf record`. The new text is much better.
___
*[`content/blog/sgx-profiler/contents.lr` line 207 at r1](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1mBvE92tKaHO7Id9TZ:-N1wXOo22oaTSwjYsB4J:b-ock2ye) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/f98b9d754d3fff4f5acb48568acac2f824e98f70/content/blog/sgx-profiler/contents.lr#L207)):*
> (I actually considered using other tools for visualization, such as KCacheGrind and Google Chrome, but they don't look up symbols).

Actually, I would put this detail/observation in your blog post. You can just lift this whole comment of yours and put it in a separate paragraph in braces.

UPDATE: Lol, you did exactly that in the next few lines :)
___
*[`content/blog/sgx-profiler/contents.lr` line 34 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wTbfg9UVWFcJ5EMPp:-N1wTbfh9uqyHPXZLBuN:b943tud) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L34)):*
> ```Markdown
> implement a feature in an inefficient way, or not provide a feature at all,
> causing the application to fall back to suboptimal behavior. A profiler helps
> with understanding where exactly the execution time is being spent).
> ```

`).` -> `.)`

Also, I would add at least one quick sentence (before `A profiler helps ...`) about the idiosyncrazies and inefficiencies of a specific Gramine environment, such as very slow fork under SGX.
___
*[`content/blog/sgx-profiler/contents.lr` line 81 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wUz4m4dk49S2PmD6i:-N1wUz4m4dk49S2PmD6j:b-kglj2h) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L81)):*
> ```Markdown
> it's possible to gather information about kernel execution, detailed processor
> performance (e.g. cache misses), system calls, and much more. (See [Brendan
> Gregg's `perf` page][brendangregg] for various examples).
> ```

`).` -> `.)`

I notice that you're using a European notation for these sentences-in-brackets. I think the American notation is more readable (when the dot is inside the brackets).
___
*[`content/blog/sgx-profiler/contents.lr` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wW6k7CqHz48LTV1EE:-N1wW6k7CqHz48LTV1EF:be2fk6c) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L110)):*
> ```Markdown
> stream of events about it from the Linux kernel.
> 
> For the time being, I abandoned `perf` and started looking for other ways to
> ```

`For the time being` reads weird to me -- like you *currently* abandoned this approach and you are *currently* looking for other ways.

Maybe `At that time,`?
___
*[`content/blog/sgx-profiler/contents.lr` line 254 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wXtsu9XjcbXFPLKxg:-N1wXtsu9XjcbXFPLKxh:b-xgolqe) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L254)):*
> ```Markdown
> 
> `perf report` does parse raw data, but it expects input (the `perf.data` file)
> in a complicated format produced by Linux kernel. The amount of data gathered by
> ```

`by the Linux kernel`
___
*[`content/blog/sgx-profiler/contents.lr` line 314 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wYTvm-j17C-X659iW:-N1wYTvm-j17C-X659iX:b7axuqs) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L314)):*
> ```Markdown
> will need to compile Gramine in debug mode, and add some options to the
> manifest. Then, running an application in Gramine will produce a file that can
> be opened by `perf report`).
> ```

I don't think you need parentheses around this paragraph at all.
___
*[`content/blog/sgx-profiler/contents.lr` line 327 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wYiFQBfGc13QPO4Mc:-N1wYiFR9LT1GhFS15CV:b-7ropln) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L327)):*
> ```Markdown
> entry, `slow`, is a function that I added to the application: it contains a
> long-running loop. Functions belonging to `libpal.so` and `libsysdb.so` come
> from the two main components of Gramine: PAL and LibOS, respectively).
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-05-13 11:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: 7 of 9 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`content/blog/sgx-profiler/contents.lr` line 34 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wTbfg9UVWFcJ5EMPp:-N1wsXQd0M6NxkHwNEo3:b2nhktp) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`).` -> `.)`

Also, I would add at least one quick sentence (before `A profiler helps ...`) about the idiosyncrazies and inefficiencies of a specific Gramine environment, such as very slow fork under SGX.
</blockquote></details>

OK.
___
*[`content/blog/sgx-profiler/contents.lr` line 81 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wUz4m4dk49S2PmD6i:-N1wtytG0Ep9sEy4LCLv:b-8huu31) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`).` -> `.)`

I notice that you're using a European notation for these sentences-in-brackets. I think the American notation is more readable (when the dot is inside the brackets).
</blockquote></details>

Yeah, it looks like I've been following the Polish punctuation rules. Fixed (and I went through the whole post to search for other instances).
___
*[`content/blog/sgx-profiler/contents.lr` line 110 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wW6k7CqHz48LTV1EE:-N1wvU5XEfqL9pJ7NF4L:b-8bcztf) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`For the time being` reads weird to me -- like you *currently* abandoned this approach and you are *currently* looking for other ways.

Maybe `At that time,`?
</blockquote></details>

I wanted to say that back then, I decided to drop `perf`, but my decision wasn't final/permanent. Does it read better now?
___
*[`content/blog/sgx-profiler/contents.lr` line 254 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wXtsu9XjcbXFPLKxg:-N1wxiSjAGSD3hp3sCfk:b-896fix) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`by the Linux kernel`
</blockquote></details>

Done.
___
*[`content/blog/sgx-profiler/contents.lr` line 314 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wYTvm-j17C-X659iW:-N1x7FizA0CSsMyXjzmT:btn8pfg) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need parentheses around this paragraph at all.
</blockquote></details>

OK. I think this paragraph is somewhat tangential, but I don't have strong feelings one way or another.
___
*[`content/blog/sgx-profiler/contents.lr` line 327 at r2](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N1wYiFQBfGc13QPO4Mc:-N1wz6q109LWX_nPjLjb:bovfy8n) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/90713d732e8466513b1c4b00bd950790c648c5a0/content/blog/sgx-profiler/contents.lr#L327)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Actually this was supposed to be an image caption, outside of the flow of the main text (and same for the first screenshot). I added some CSS to make it appear like a caption. 

(Unfortunately that means I cannot use Markdown here: apparently in this Python parser, once you escape to HTML, there's no going back...)


<!-- Sent from Reviewable.io -->

2022-05-13 11:54 UTC, dimakuv approved these changes, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-05-30 20:59 UTC, mkow requested changes
> Reviewed 5 of 9 files at r1, 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3Lkc7A2sCg4yMuQELz:-N3Lkc7A2sCg4yMuQEM-:b9u6w6q) (no related file):*
That was a good read!

___
___
*[`content/blog/sgx-profiler/contents.lr` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3Lf6vJ2_FtzgeHm0Ny:-N3Lf6vKDqfpZk1hfgLr:b-y5zxqr) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L15)):*
> ```Markdown
> 
> [Gramine] is a framework for running Linux applications under non-standard
> environments, with [Intel SGX] enclaves as currently the main use case. In the
> ```

I think this would read more naturally, at least for me. Not blocking.



_Suggestion:_
```Markdown
currently with [Intel SGX] enclaves as the main use case
```
___
*[`content/blog/sgx-profiler/contents.lr` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LfM408EyJlPqvvl2O:-N3LfM408EyJlPqvvl2P:buukpfo) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L23)):*
> ```Markdown
> [prev]: https://gramineproject.io/blog/gdb-support-in-gramine/
> 
> [Profilers] allow analyzing a program behavior, for instance by presenting
> ```

I think in this meaning it's uncountable?



_Suggestion:_
```Markdown
program behavior
```
___
*[`content/blog/sgx-profiler/contents.lr` line 344 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LjSiv4iQWp_9lFaFY:-N3LjSiv4iQWp_9lFaFZ:bib9ug9) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L344)):*
> ```Markdown
> One frequently encountered issue was applications mapping too much memory. On
> Linux, `mmap` is usually cheap, so you can afford to map a large area without
> using it: the actual memory will be allocated and zeroed only when accessed by
> ```

Nitpick: it's even stronger than this: only after it was written for the first time (after mmap everything is a CoW mapping of the zero page).



_Code quote:_
```Markdown
only when accessed
```
___
*[`content/blog/sgx-profiler/contents.lr` line 352 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LjmzqEZT8MyQD1DyU:-N3LjmzqEZT8MyQD1DyV:b-hrbdc7) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L352)):*
> ```Markdown
> 
> [enclave-size]: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#enclave-size
> [glibc-malloc-tuning]: https://gramine.readthedocs.io/en/latest/devel/performance.html#glibc-malloc-tuning
> ```

Maybe it would be a better idea to bind all these doc links to the current release, so they won't become dangling in the future?



_Code quote:_
```Markdown
https://gramine.readthedocs.io/en/latest
```


<!-- Sent from Reviewable.io -->

2022-06-08 15:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: 7 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`content/blog/sgx-profiler/contents.lr` line 15 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3Lf6vJ2_FtzgeHm0Ny:-N42wSfd4bvNoTGYJgXU:b-896fix) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this would read more naturally, at least for me. Not blocking.
</blockquote></details>

Done.
___
*[`content/blog/sgx-profiler/contents.lr` line 23 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LfM408EyJlPqvvl2O:-N42yjDF3lRF3XHir8U2:b-up1obo) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think in this meaning it's uncountable?
</blockquote></details>

Right, I'm not sure what I wanted here. Fixed.
___
*[`content/blog/sgx-profiler/contents.lr` line 344 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LjSiv4iQWp_9lFaFY:-N42wpOP8HQCqSQuvoQ5:b-8njp3) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L344)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nitpick: it's even stronger than this: only after it was written for the first time (after mmap everything is a CoW mapping of the zero page).
</blockquote></details>

Right. Reworded.
___
*[`content/blog/sgx-profiler/contents.lr` line 352 at r3](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-N3LjmzqEZT8MyQD1DyU:-N42yo1QDnbHDvpmtfhF:bmuhtzc) ([raw file](https://github.com/gramineproject/gramineproject.io/blob/a48f74a0d345cccc38a8e2b2f51083e6cfa94504/content/blog/sgx-profiler/contents.lr#L352)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe it would be a better idea to bind all these doc links to the current release, so they won't become dangling in the future?
</blockquote></details>

You're right, I wanted to do that but forgot. I updated all the links, and actually bumped them to v1.2 since it's published now. I also updated the bit about VTune.


<!-- Sent from Reviewable.io -->

2022-06-08 16:01 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2022-06-08 16:39 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-06-08 22:56 UTC, woju approved these changes
> Reviewed 1 of 9 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: 8 of 9 files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-08 23:03 UTC, woju reviewed
Deployed (in UTC it was still 8.06.2022!), but I didn't notice I couldn't push because @mkow and @dimakuv's reviews were dismissed. Plz approve and merge as is.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4#-:-N44YSN03Vd4cmlZBzsr:bz1jhb8)* status: 8 of 9 files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2022-06-08 23:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-06-09 06:52 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gramineproject.io/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-06-09 06:54 UTC, merged